version: '3'

services:
  api:
    tty: true
    build: .
    ports:
      # ホスト:コンテナ
      - "3000:8080"
    depends_on:
      - mysql
    container_name: api

  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: dojo_db
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dojo_user
      MYSQL_PASSWORD: userpass
    container_name: mysql
    volumes:
      # db-data という volume を作成
      - db-data:/var/lib/mysql

# docker のリソースとしてのvolume
volumes:
  # ボリュームの名前を指定して保存
  db-data:
